### ISSUE TITLE
Load locale directly from public

### ISSUE THREAD

**Issue by Dmi3yy** [robinkloeckner/vue3-vite-i18n-lazy#1]
In my case i set locale after user auth, but now try just load locale directly:

put code in my view:
`
onBeforeMounted(() => {
    setLocale('de');
})
`

and now i can use locale directly from public folder. 

This approach is important when you want to be able to change the translation texts without having to re-build the project.

I am still just starting to work with VUE and maybe you know a more elegant solution to this issue

**Comment by robinkloeckner** [comment]
I am not sure I understand you correctly? What do you mean with loading the locale directly? 

The idea in the [article](https://medium.com/gitconnected/how-to-load-i18n-locales-asynchronously-in-vue-3-vite-9e7301c52f19) the repository belongs to is to load additional locales from a server if needed. Therefore some locale resource files are placed in `/src/locales/` and some in `/public/locales/`. Those in `/src/locales` are pre-compiled and bundled during the build process. The ones in `/public/locales/` must be fetched and compiled during runtime.

Can you explain in more detail what you are trying to achieve?
